---
title: "GES 109: Organização e Apresentação de Dados"
execute: 
  freeze: false
---

Essa página contém o resumo dos tópicos e avaliações da disciplina. O cronograma será atualizado ao longo do semestre e o tempo destinado aos tópicos pode ser ajustado se necessário.

::: {style="background-color: #99b3ff; padding: 10px;"}
⚠️ Devido ao perído de [greve docente](https://ufla.br/noticias/institucional/16735-ufla-recebe-comunicado-de-deflagracao-da-greve-dos-professores) e a [suspensão do calendário](https://ufla.br/noticias/institucional/16749-ufla-suspende-calendario-escolar-2024-dos-cursos-presenciais-de-graduacao-e-pos-graduacao#:~:text=Portal%20UFLA&text=Est%C3%A3o%20suspensos%20os%20cronogramas%20dos,partir%20da%20data%20de%20publica%C3%A7%C3%A3o.) da Universidade Federal de Lavras, as atividades da GES-109 estão <u>pausadas</u>. 
:::

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1uDx0kdEL0ZIdU_yFUySETuZTFyCQgDzC-2qPQmdENcw/edit?usp=sharing")
```

```{r}
#| echo: false
d |>
  #filter(!is.na(session)) |>
  select(-Ds, -Conteúdo, -Material) |>
  mutate(Data = as.Date(Data)) |>
  gt() |>
  fmt_date(Data, date_style = 10) |>
  sub_missing(columns = c(Semana, Preparação, Tópico, Atividade), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(Semana)
  ) |>
  cols_align(
    align = "right", 
    columns = c(Data)
  ) |>
  cols_align(
    align = "left", 
    columns = c(Tópico, Preparação, Atividade)
  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(Data, Tópico, Preparação)
    )
  ) |>
  fmt_markdown(
    columns = c(Tópico, Preparação, Atividade)
  ) |>
  cols_width(
    Semana ~ px(100),
    Data ~ px(100), 
    Preparação ~ px(200),
    Tópico ~ px(250),
    Atividade ~ px(150)
  ) |>
  cols_label_with(fn = function(x) {
    x %>%
      toupper() %>%
      stringr::str_replace_all("^|$", "**") %>%
      gt::md()
  })|>
  tab_options(table.font.size = 13) |>
  opt_row_striping()
```
